# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DemandPredictor
                                 A QGIS plugin
 This plugin takes in Irish census data as a csv and then according to the distribution function provided it predicts demand for small areas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-12-06
        copyright            : (C) 2021 by Fiachra Barry
        email                : fiachrabarry@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Fiachra Barry'
__date__ = '2021-12-06'
__copyright__ = '(C) 2021 by Fiachra Barry'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DemandPredictor class from file DemandPredictor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .demand_predictor import DemandPredictorPlugin
    return DemandPredictorPlugin()
